import './globals.css'
import { Inter } from 'next/font/google'
import { UserContextProvider } from '@/ContextUser'
import AuthProvider from '@/AuthProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Iniciar Sesion',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <UserContextProvider>
          <AuthProvider>
            {children}
          </AuthProvider>
        </UserContextProvider>
      </body>
    </html>
  )
}
