import Sidebar from '@/Sidebar/Sidebar'
import './globals.css'
import { Inter } from 'next/font/google'
import Container from '@/Layout/Container'
import { cookies } from 'next/headers'
import { UserContextProvider } from '@/contextUser'
import BreadCrumb from '@/BreadCrumb/BreadCrumb'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Iniciar Sesion',
  description: 'Generated by create next app'
}
export const isLoggin = () => {
  const cookieStore = cookies()
  const accessToken = cookieStore.get('accessToken')
  return { accessToken }
}

export default function RootLayout({ children }) {
  const { accessToken } = isLoggin()

  if (!accessToken) {
    // redirect('/login')
  }

  return (
    <html lang='en'>
      <body className={inter.className}>
        <UserContextProvider>
          {
            accessToken
              ? (
                <>
                  <Sidebar />
                  <Container>
                    <BreadCrumb />
                    {children}
                  </Container>
                </>)
              : children
          }
        </UserContextProvider>

      </body>
    </html>
  )
}
